function y = BUTTfil(x) % you know what it is. #LabTraditionsofInappropNames #analparam
%BUTTERFILTERFD Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 8.5 and the DSP System Toolbox 9.0.
% Generated on: 26-Sep-2015 15:45:10

%#codegen

% To generate C/C++ code from this function use the codegen command.
% Type 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    % The following code was used to design the filter coefficients:
    %
    % N    = 10;       % Order
    % F3dB = 0.03072;  % 3-dB Frequency
    %
    % h = fdesign.highpass('n,f3db', N, F3dB);
    %
    % Hd = design(h, 'butter', ...
    %     'SystemObject', true);
    
    Hd = dsp.BiquadFilter( ...
        'Structure', 'Direct form II', ...
        'SOSMatrix', [1 -2 1 1 -1.96113096905514 0.970299660111203; 1 -2 1 1 ...
        -1.90725724249449 0.916174062786871; 1 -2 1 1 -1.86370613792218 ...
        0.872419347833981; 1 -2 1 1 -1.83329151264088 0.841862527917449; 1 -2 1 ...
        1 -1.81769634500692 0.826194449663916], ...
        'ScaleValues', [0.982857657291584; 0.955857826320341; ...
        0.934031371439041; 0.918788510139583; 0.910972698667708; 1]);
end

y = step(Hd,x);


